name: linux-ubuntu-latest-32

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cr,,oss-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container:
      image: i386/ubuntu:latest

    steps:
    
    - name: Install sudo package
      run: apt update && apt install -y sudo
        
    - name: Install dependencies
      run: sudo apt-get install -y git build-essential cmake file make libpng-dev libfreeimage-dev
      
    - name: git pull
      run: git clone --recurse-submodules https://github.com/trufanov-nok/c44-freeimage.git

    - name: Configure CMake
      run: mkdir -p c44-freeimage/build && cd c44-freeimage/build && cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=/usr ..
      
    - name: Build
      # Build your program with the given configuration
      run: cd c44-freeimage/build && make -j6

    - name: Test
      run: cd c44-freeimage/build && ctest -C ${{env.BUILD_TYPE}}

    - name: Package
      run: cd c44-freeimage/build && cpack
      
    - name: Archive package
      uses: actions/upload-artifact@v1
      with:
          name: deb package ubuntu 32bit
          path: c44-freeimage/build/c44-freeimage-3.5.28-Linux.deb
